### ISSUE TITLE
antd 4.7.1报错了

### ISSUE THREAD

**Issue by mycode65678** [EddieUp/antd-table-saveas-excel#25]
[@umijs/runtime] load component failed Error: Module "./antd-table-saveas-excel" does not exist in container.
while loading "./antd-table-saveas-excel" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:702:11 
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.f6dd37b3.async.js:1173:68)
    at Route
    at Switch
    at Route
    at Switch
    at WithExceptionOpChildren (http://localhost:8000/.umi__plugin-layout__Layout.js:222:24)
    at main
    at Basic (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.ab762649.async.js:429:25)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.ab762649.async.js:412:66)
    at ErrorBoundary (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_hooks_useFo-3b2c40.092d9fce.async.js:4492:87)
    at FormProvider (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_icons_es_icons_LoadingOutlined_js-node_modules_antd_es__util_-a9dcf0.4f4c72e4.async.js:2500:31)
    at LocaleProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.b28d7b57.async.js:896:87)
    at ProviderChildren (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.b28d7b57.async.js:726:24)
    at LocaleReceiver (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_context_js.6b64ec04.async.js:720:87)
    at ConfigProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.b28d7b57.async.js:834:13)
    at SWRConfig$1 (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-provider_es_index_js.af96701f.async.js:2267:23)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-provider_es_index_js.af96701f.async.js:236:23)
    at WrapContent (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_hooks_useFo-3b2c40.092d9fce.async.js:879:21)
    at div
    at section
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.ab762649.async.js:444:63)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.ab762649.async.js:412:66)
    at div
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_hooks_useFo-3b2c40.092d9fce.async.js:5786:31)
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_hooks_useFo-3b2c40.092d9fce.async.js:289:67)
    at BasicLayout (http://localhost:8000/.umi__plugin-layout__Layout.js:701:24)
    at http://localhost:8000/.umi__plugin-layout__Layout.js:41:19
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.f6dd37b3.async.js:1173:68)
    at Route
    at Switch
    at Router (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.f6dd37b3.async.js:3489:30)
    at RouterComponent (http://localhost:8000/mf-dep_vendors-node_modules_babel_runtime_helpers_esm_objectWithoutPropertiesLoose_js-node_modules_b-e4eb9f.e58b0f0b.async.js:610:23)
    at http://localhost:8000/umi.js:1335:24
    at http://localhost:8000/umi.js:1959:23

**Comment by EddieUp** [comment]
我在codesandbox里试了antd 4.7.1，没有发现问题，可以给个出错的在线例子么？
